ToDo/config/routes.rb
Rails.application.routes.draw do

  get "reminders/index/:id" => "reminders#make_finish", as: :make_finish_reminder
  resources :reminders

  root "reminders#index"

end

ToDo/app/models/reminder.rb
class Reminder < ActiveRecord::Base
end

ToDo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ToDo/app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
	include ActionController::ImplicitRender

	def index
		@finished = Reminder.where(finished: true)
		@unfinished = Reminder.where(finished: false)
	end

	def show
		@reminder = Reminder.find(params[:id])
	end

	def new
		@reminder = Reminder.new
	end

	def edit
		@reminder = Reminder.find(params[:id])
	end

	def create
		if @reminder = Reminder.create(cr_params)
			redirect_to(:action => "show", :id => @reminder.id)
		else
			render "new"
		end
	end

	def update
		@reminder = Reminder.find(params[:id])
		if @reminder.update_attributes(upd_params)
			redirect_to(:action => "show", :id => @reminder.id)
		else
			render "edit"
		end
	end

	def make_finish
		@reminder = Reminder.find(params[:id])
		@reminder.finished = toggle(@reminder.finished)
		if @reminder.save
			redirect_to(:action => "index")
		else
			render "index"
		end
	end

	def destroy
		@reminder = Reminder.find(params[:id])
		if @reminder.destroy
			redirect_to(:action => "index")
		else
			render "index"
		end
	end

	private
	def cr_params
		params.require(:reminder).permit(:title, :description, :due_date, :priority, :finished)
	end

	def upd_params
		params.require(:reminder).permit(:description, :due_date, :priority, :finished)
	end

	def toggle(number)
		if number == 0
			return 1
		elsif number == 1
			return 0
		else
			return 0
		end
	end
end

ToDo/app/helpers/application_helper.rb
module ApplicationHelper
end

ToDo/app/helpers/reminders_helper.rb
module RemindersHelper
end

ToDo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Q01Pcalendar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ToDo/app/views/reminders/edit.html.erb
<%= form_for(@reminder) do |r| %>
	<h2><%= @reminder.title %></h2>
<div class="well">

	<p>
	<%= r.label :description, "Description: " %>
	<%= r.text_area :description%>
	</p>
	
	<p>
	<%= r.label :due_date, "Deadline: " %>
	<%= r.text_field :due_date %>
	</p>

	<p>
		<%= r.label :priority, "Choose the priority" %>
		<p><%= r.select :priority, [["Low",1], ["Medium", 2], ["High", 3]] %></p>
	</p>

	<p>
		<%= r.label :finished, "Finished this task already?" %>
		<p><%= r.check_box :finished %></p>
	</p>
	<p>	
		<%= r.submit %>
	</p>
	<p>
		<%= link_to "Back to all", reminders_path%> |
		<%= link_to "Delete", reminder_path(r), :confirm => "Are you sure?", :method => :delete %></p>	
	</p>
<% end %>
</div>

ToDo/app/views/reminders/index.erb
<h1>Overview of all todo's</h1>
<h4><%= link_to "Create new", new_reminder_path %></h4>
<div class="container">
  <h3>Unfinished</h3>
  <% @unfinished.each do |ur| %>
      <div class="well">
        <h4>&quot;<%= link_to ur.title, reminder_path(ur) %>&quot;</h4>
        <div>Priority: <%= ur.priority %> </div>
        <div>Deadline: <%= ur.due_date %></div>
        <p><%= link_to "Edit", edit_reminder_path(ur)%> |
          <%= link_to "Finished", make_finish_reminder_path(ur)%> |
          <%= link_to "Delete", reminder_path(ur), :confirm => "Are you sure?", :method => :delete %></p>
      </div>
  <% end %>
</div>

<div class="container">
  <h3>Finished</h3>
  <% @finished.each do |fr| %>
      <div class="well">
        <h4>&quot;<%= link_to fr.title, reminder_path(fr) %>&quot;</h4>
        <div>Priority: <%= fr.priority %> </div>
        <div>Deadline: <%= fr.due_date %></div>
        <p><%= link_to "Edit", edit_reminder_path(fr)%> |
          <%= link_to "Not finished", make_finish_reminder_path(fr)%> |
          <%= link_to "Delete", reminder_path(fr), :confirm => "Are you sure?", :method => :delete %></p>
      </div>
  <% end %>
</div>

ToDo/app/views/reminders/new.html.erb
<h2>Create new reminder</h2>

<div class="well">
<%= form_for(@reminder) do |r| %>

	<p>
	<%= r.label :title, "Title: " %>
	<%= r.text_field :title %>
	</p>

	<p>
	<%= r.label :description, "Description: " %>
	<%= r.text_area :description %>
	</p>
	
	<p>
	<%= r.label :due_date, "Deadline: " %>
	<%= r.text_field :due_date %>
	</p>

	<p>
		<%= r.label :priority, "Choose the priority" %>
		<p><%= r.select :priority, [["Low",1], ["Medium", 2], ["High", 3]] %></p>
	</p>

	<p>
		<%= r.label :finished, "Finished this task already?" %>
		<p><%= r.check_box :finished %></p>
	</p>

	<%= r.submit %>

<% end %>
</div>